url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Jekyll Foundation Template" # the name of your site, e.g. ACME Corp.
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

sass:
  load_paths:
    - _sass
    - node_modules/foundation-sites/scss
  #style: compressed
  #sourcemap: false

exclude: 
  - package.json
  - package-lock.json

foundation_dir: "path to foundation_dir"

site_resources:
  # foundation
  - name: 'foundation.min.js' 
    src_base: 'node_modules/foundation-sites/dist/js'
    file: 'foundation.min.js'
    dest_base: 'assets/js/vendor' 
  - name: 'foundation.js.map' 
    src_base: 'node_modules/foundation-sites/dist/js'
    file: 'foundation.min.js.map'
    dest_base: 'assets/js/vendor'   
  - name: 'foundation.min.css' 
    src_base: 'node_modules/foundation-sites/dist/css'
    file: 'foundation.min.css'
    dest_base: 'assets/css/vendor'     
  - name: 'foundation.min.css.map' 
    src_base: 'node_modules/foundation-sites/dist/css'
    file: 'foundation.min.css.map'
    dest_base: 'assets/css/vendor'         
  # jquery  
  - name: 'jquery.min.js'
    src_base: 'node_modules/jquery/dist'
    file: 'jquery.min.js'
    dest_base: 'assets/js/vendor' 
  - name: 'jquery.min.map'
    src_base: 'node_modules/jquery/dist'
    file: 'jquery.min.map'
    dest_base: 'assets/js/vendor'   
# what-input
  - name: 'what-input.min.js'
    src_base: 'node_modules/what-input/dist'
    file: 'what-input.min.js'
    dest_base: 'assets/js/vendor' 
  - name: 'what-input.min.js.map'
    src_base: 'node_modules/what-input/dist/maps'
    file: 'what-input.min.js.map'
    dest_base: 'assets/js/vendor/maps' 